export * from './my-estates/my-estates';
//export * from './tournaments/tournaments';
export * from './estate-detail/estate-detail';
export * from './estates/estates';
export * from './game/game';
export * from './locations/locations';
export * from './estate-home/estate-home';
export * from './map/map';
export * from './similar/similar';